name: R7 Scan
on:
  push:
    branches-ignore:
     - master
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - id: my-scan
        uses: rapid7/insightappsec-scan-github-actions@v1.3.5
        with:
          region: "us"
          api-key: ${{ secrets.GHACTIONSR7API}}
          scan-config-id: "3e3d9733-d7ca-444f-ab17-ad7bd18e2765"
          vuln-query: "vulnerability.vulnerabilityScore > 4"
      - name: Upload findings
        if: always()
        run: echo "${{ steps.my-scan.outputs.scan-findings }}"
